language: c
compiler: gcc

sudo: required

services:
    - docker

before_install:
    - sudo apt-get update
    - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
    - docker build -t travisci/systemd .
    - docker ps -a
    - docker run -dit travisci/systemd bash

# Run standard script stage before the Coverity Scan
script: 
    - docker --version
    - docker ps -a
    - |
       if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then
        docker exec -ti travisci/systemd meson build
        docker exec -ti travisci/systemd dinja -C build
        docker exec -ti travisci/systemd dinja -C build test
       fi

after_failure: docker exec -ti travisci/systemd cat test-suite.log

branches:
    only:
        travis-docker

# notifications:
#   irc:
#     channels:
#       - "irc.freenode.org#systemd"
#     on_success: change
#     on_failure: always

# env:
#     global:
#         # COVERITY_SCAN_TOKEN
#         - secure: "TBD"  # TODO

# addons:
#     coverity_scan:
#         project:
#             name: CermakM/systemd  # FIXME
#             description: systemd System and Service Manager

#         notification_email: macermak@redhat.com

#         # Commands to prepare for build
#         build_command_prepend: meson build

#         # The command that will be added as an argument to "cov-build" to compile your project for analysis,
#         build_command: ninja -C build

#         branch_pattern: coverity_scan
