language: c
compiler: gcc

sudo: required

services:
    - docker

before_install:
    - sudo apt-get update
    - echo "ENV GIT_SHA ${TRAVIS_COMMIT}" >> Dockerfile
    - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
    - docker --version

install:
    - docker build -t ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT} --pull=true .

# Run standard script stage before the Coverity Scan
script: 
    - docker run --privileged -dit --name ${TRAVIS_COMMIT} ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT} bash
    - docker ps -a
    - |
       if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then
        docker exec -ti ${TRAVIS_COMMIT} meson build
        docker exec -ti ${TRAVIS_COMMIT} ninja -C build
        docker exec -ti ${TRAVIS_COMMIT} ninja -C build test
       fi

after_failure: 
  - docker exec -ti cat build/meson-logs/testlog.txt

branches:
    only:
        travis-docker

env:
    global:
        - DOCKER_REPOSITORY=travis_ci/systemd

before-script:
    - env > .env

# notifications:
#   irc:
#     channels:
#       - "irc.freenode.org#systemd"
#     on_success: change
#     on_failure: always

# env:
#     global:
#         # COVERITY_SCAN_TOKEN
#         - secure: "TBD"  # TODO

# addons:
#     coverity_scan:
#         project:
#             name: CermakM/systemd  # FIXME
#             description: systemd System and Service Manager

#         notification_email: macermak@redhat.com

#         # Commands to prepare for build
#         build_command_prepend: meson build

#         # The command that will be added as an argument to "cov-build" to compile your project for analysis,
#         build_command: ninja -C build

#         branch_pattern: coverity_scan
